FROM node:14

WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY ./ ./

RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev
RUN npm install sqlite3 --build-from-source
RUN npm install --force


EXPOSE 3001
CMD ["npm", "start"]
